package com.springboot.learn.Day_03_03_many_to_many_association_model_for_join_table.repository;

import com.springboot.learn.Day_03_03_many_to_many_association_model_for_join_table.entity.Enrollment;
import com.springboot.learn.Day_03_03_many_to_many_association_model_for_join_table.entity.EnrollmentId;
import org.springframework.data.jpa.repository.JpaRepository;

public interface EnrollmentRepository extends JpaRepository<Enrollment, EnrollmentId> {
}
