server:
  port: 8000

spring:
  application:
    name: jpaMapping

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/LearnSpringboot
    username: root
    password: Kul&12345