server:
  port: 8080

spring:
  redis:
    port: 6379
  application:
    name: jpaMapping

  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/learnspringboot
    user: root
    password: Kul&12345
    locations: classpath:db/migration

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.enable_lazy_load_no_trans: true

  datasource:
    url: jdbc:mysql://localhost:3306/LearnSpringboot
    username: root
    password: Kul&12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
